# Generated by Django 4.1.7 on 2023-03-13 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatOwner', models.CharField(max_length=16)),
                ('chatTitle', models.CharField(max_length=256)),
                ('createdData', models.DateTimeField(default=django.utils.timezone.now)),
                ('chatReceiver', models.CharField(max_length=16)),
                ('chatContent', models.TextField()),
            ],
        ),
    ]
