# Generated by Django 4.1.7 on 2023-03-29 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welcome', '0002_alter_chat_chatowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicTitle', models.CharField(max_length=128)),
                ('creataDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('topicOwner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatTopic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='replys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyContent', models.TextField()),
                ('replyBelongsTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replyBelong', to='welcome.chattopics')),
                ('replyerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
