# Generated by Django 4.1.7 on 2023-03-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_chattopics_replys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replys',
            name='replyBelongsTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replyBelong', to='welcome.chat'),
        ),
    ]
