# Generated by Django 4.1.7 on 2023-03-29 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_alter_replys_replybelongsto'),
    ]

    operations = [
        migrations.AddField(
            model_name='replys',
            name='replyDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
