# Generated by Django 4.1.7 on 2023-04-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0008_alter_chat_chatreceiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
