# Generated by Django 4.1.7 on 2023-04-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_chat_opened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='createdData',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='opened',
            new_name='is_viewed',
        ),
        migrations.AddField(
            model_name='chat',
            name='viewedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
