# Generated by Django 4.1.7 on 2023-04-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0010_rename_createddata_chat_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
