# Generated by Django 4.1.7 on 2023-04-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0011_chat_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('cch_user', 'CCH User'), ('htc_user', 'HTC User'), ('aicenter', 'AI Center')], default='cch_user', max_length=10),
        ),
    ]
