# Generated by Django 4.1.7 on 2023-04-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0012_alter_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
